FROM node:16-alpine AS api

WORKDIR /app
RUN mkdir -p /var/logs
RUN chmod +w /var/logs

COPY package.json ./
COPY package-lock.json ./
COPY . .

RUN apk update \
    && apk add tzdata \
    && cp /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

RUN npm install --silent --legacy-peer-deps

CMD ["npm", "run", "server:dev"]




