FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY ./ ./

RUN npm install --silent --legacy-peer-deps
RUN npm install react-scripts@5.0.1 -g --silent 
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY ./docker/nginx/nginx.dev.conf /etc/nginx/nginx.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]